name: build-and-deploy
on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    name: Build and Deploy 💪
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Check Branch
        run: git branch

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run-script build

      - name: Git Status
        run: git status

      - name: Commit Changes
        uses: EndBug/add-and-commit@v5
        with:
          add: 'build'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GH Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
